Feature/payment receipt support
mobilecoinofficial/desktop-wallet pull request #172
Opened 2021-08-17 20:24 UTC by BrianCorbin

Adding support for generating receiver receipts and transaction log confirmations.

2021-08-19 21:33 UTC, fktt22 commented on app/components/ConfirmDeleteWallet.dialog/ConfirmDeleteWalletDialog.view.tsx
> +  const handleOnSubmit = () => confirm();
Better:

`const handleOnSubmit = confirm;`

2021-08-19 21:33 UTC, fktt22 commented on app/components/ConfirmDeleteWallet.dialog/ConfirmDeleteWalletDialog.view.tsx
> +      }}
Similarly:

`onClose = { cancel }`

2021-08-19 21:34 UTC, fktt22 commented on app/components/ConfirmDeleteWallet.dialog/ConfirmDeleteWalletDialog.view.tsx
> +        </Typography>
Texts must be from i18n files

2021-08-19 21:34 UTC, fktt22 commented on app/components/ConfirmDeleteWallet.dialog/ConfirmDeleteWalletDialog.view.tsx
> +                    </Typography>
Texts must be from i18n files

2021-08-19 21:37 UTC, fktt22 commented on app/pages/Auth/UnlockWallet.view/UnlockWallet.view.tsx
> +            </Button>
All texts must come from i18n files

2021-08-19 21:39 UTC, fktt22 commented on app/pages/History/TransactionDetails.view/TransactionDetails.view.tsx
> +      )}
Texts must be from i18n files

2021-08-19 21:39 UTC, fktt22 requested changes
Please review comments, in particular about i18n

2021-08-20 14:21 UTC, BrianCorbin commented on app/components/ConfirmDeleteWallet.dialog/ConfirmDeleteWalletDialog.view.tsx
> +        </Typography>
addressed in next PR

2021-08-20 14:21 UTC, BrianCorbin commented on app/components/ConfirmDeleteWallet.dialog/ConfirmDeleteWalletDialog.view.tsx
> +                    </Typography>
addressed in next PR

2021-08-20 14:22 UTC, BrianCorbin commented on app/pages/Auth/UnlockWallet.view/UnlockWallet.view.tsx
> +            </Button>
addressed in next PR

2021-08-20 21:11 UTC, fktt22 commented on app/components/ConfirmDeleteWallet.dialog/ConfirmDeleteWalletDialog.view.tsx
> +                      backed up.
This needs translation from i18n

2021-08-20 21:13 UTC, fktt22 approved these changes

2021-08-21 00:42 UTC, merged