Feature/work with pin
mobilecoinofficial/desktop-wallet pull request #41
Opened 2021-02-15 23:55 UTC by fktt22

Soundtrack of this PR: [Harlem Nocturne by Duke Ellington](https://www.youtube.com/watch?v=uIkekMoEQY4) PINs, security, checks... a throwback to noir films with hard private detectives!

### Motivation

Adding the usage of a PIN whenever MOB are sent.

### In this PR

Addition of a (hashed) PIN to the Electron store
Addition of hashing methods as utilities
Addition of a component to set the PIN in Settings

### Caveats

There's no way now to remove the PIN after having set one.

### Future Work

Add PIN input and validation to sending MOB
Add unit testing

### Screen Shots

![image](https://user-images.githubusercontent.com/78449916/108002968-ea045d00-6fcf-11eb-90c4-c7bc54043a08.png)
![image](https://user-images.githubusercontent.com/78449916/108002955-e07af500-6fcf-11eb-919c-87ef97a9d85a.png)

### Testing
```
Test Suites: 25 passed, 25 total
Tests:       107 passed, 107 total
Snapshots:   8 passed, 8 total
Time:        34.239 s
Ran all test suites.
Done in 37.92s.
```

2021-02-17 23:13 UTC, fktt22 commented
I had to modify the confirmation form, which was too high, in order to make space for the PIN entry. 

![image](https://user-images.githubusercontent.com/78449916/108280229-a2f7a280-715c-11eb-8212-c0c7ec5e547a.png)

2021-02-17 23:14 UTC, fktt22 commented
On successful PIN entry, the SEND button is enabled.

![image](https://user-images.githubusercontent.com/78449916/108280311-c02c7100-715c-11eb-99f4-dabe167daaa8.png)

2021-02-18 00:01 UTC, fktt22 commented
The PIN is input in the same way for a gift.

![image](https://user-images.githubusercontent.com/78449916/108284073-3fbd3e80-7163-11eb-9ccc-693979e1b395.png)

2021-02-20 21:55 UTC, davidyhall requested changes
Looks great! 3 small requests, the rest can be CBB.

1. The threshold should be inclusive. So a threshold of 1 MOB should trigger at 1 or great.
2. Let's require a the user's password to set/change the PIN
3. We're retiring `mobilecoind` (in the wallet!) so instead, lets name the file something like `mobilecoinConfig.json`

There are things that I think we can loop back on and improve later, but I think this gets the feature up and running!

2021-02-20 22:07 UTC, davidyhall commented
Just a note: right now, the code hashes the PIN to keep the plain-text hidden. But it's a trivial operation to exhaust the options and discover the pin. The PIN isn't meant to function in the same capacity as the password, but there is a danger that the user has the same PIN for all of their devices/cards (highly not recommended!). So we don't want to compromise their personal PIN. We'll loop back and encrypt the PIN the same way we encrypt the entropy. And when the user unlocks the wallet with their password, we can keep the PIN in memory

2021-02-22 23:09 UTC, fktt22 commented
Require password to set/change PIN.
Show previous minimum for PIN.
Make limit inclusive (>=) instead of exclusive (>).
Minor fixes elsewhere.

2021-02-23 17:56 UTC, davidyhall approved these changes
LGTM!

2021-02-23 17:56 UTC, davidyhall commented on app/layouts/DashboardLayout/TopBar/SyncStatus.tsx
> +              variant="determinate"
🥇

2021-02-23 17:56 UTC, davidyhall commented on app/utils/LocalStore.ts
> +    return this.store.get(schemaKeys.NAME) as string;
TIL `as string` assertion.

2021-02-23 21:23 UTC, merged