Internationalization Added to Menu Bar
mobilecoinofficial/desktop-wallet pull request #49
Opened 2021-03-03 22:40 UTC by BrianCorbin

Soundtrack of this PR: [link to song that really fits the mood of this PR]()

### Motivation

i18next is a pain, and for some reason the app was no longer working on Mac's when performing yarn start OR yarn package.

### In this PR

Reverting to the last stable main section and reimplemented, is currently stable.

### Caveats

### Future Work

### Screen Shots

### Testing
Test Suites: 25 passed, 25 total
Tests:       108 passed, 108 total
Snapshots:   8 passed, 8 total
Time:        29.08 s
Ran all test suites.
✨  Done in 32.22s.

2021-03-04 01:30 UTC, davidyhall requested changes
Great start!

I'm not seeing the menu correctly build when running `yarn package` -- it looks like it's generating the default menu.

2021-03-04 01:30 UTC, davidyhall commented on app/menuFactory.js
> +import otherTemplate from './menus/other-menu';
Let's keep filenames camelCase

2021-03-04 01:30 UTC, davidyhall commented on app/menuFactory.js
> +import { Menu } from 'electron';
Let's use Typescript

2021-03-04 01:30 UTC, davidyhall commented on app/i18n.ts
> +    fallbackLng: 'en',
I think long term their may be different en versions. also fine with renaming to `'en-US'`

2021-03-04 01:30 UTC, davidyhall commented on app/i18next.config.client.js
> +  saveMissing: true,
We won't need saveMissing

2021-03-04 01:30 UTC, davidyhall commented on app/i18next.config.client.js
> +  whitelist: config.languages,
Double check this key. I think it may have been deprecated for `supportedLngs` -- I would check all the keys tbh.

2021-03-05 07:09 UTC, davidyhall requested changes
It looks like the menu is still not building correctly in `yarn package`

2021-03-05 21:16 UTC, BrianCorbin commented
Unnecessary since all of these changes are captured in [PR#50](https://github.com/mobilecoinofficial/desktop-wallet/pull/50)

2021-03-05 21:16 UTC, closed without merging